BASE: ['']
DATA:
  FS: 30
  DATASET: UBFC
  DO_PREPROCESS: True
  DATA_FORMAT: NDCHW
  TEST_DATA_PATH: "/Users/zhangxiaoyu/Documents/Toolbox/DeepLearningProject/UBFC-Valid"
  PREPROCESS :
    DATA_TYPE: ['Normalized','Standardized']
    LABEL_TYPE : Normalized
    CLIP_LENGTH: 180
    CROP_FACE: True
    H: 72
    W: 72
  EXP_DATA_NAME: "test_UBFC_Tscan_SizeW72_SizeH72_ClipLength180_DataTypeNormalized_Standardized_LabelTypeNormalized"
DEVICE: cpu
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 20
INFERENCE:
  BATCH_SIZE: 1
  MODEL_PATH: /Users/zhangxiaoyu/Documents/Toolbox/DeepLearningProject/rPPG-Toolbox-1/PreTrainedModels/UBFC_SizeW72_SizeH72_ClipLength180_DataTypeNormalized_Standardized_LabelTypeNormalized/tscan_train_ubfc.pth
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
